# Generated by Django 5.1.2 on 2024-10-28 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='client_email',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='employees',
            name='email',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
