# Generated by Django 5.1.2 on 2024-10-28 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_clients_client_email_alter_employees_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sub_categories',
            name='sub_category_description',
        ),
    ]
